export const OBTENER_CABALLOS = 'OBTENER_CABALLOS'
export const AGREGAR_CABALLO = 'AGREGAR_CABALLO'
export const ELIMINAR_CABALLO = 'ELIMINAR_CABALLO'
export const ACTUALIZAR_CABALLO = 'ACTUALIZAR_CABALLO';
export const LIMPIAR_CABALLOS = 'LIMPIAR_CABALLOS';
export const CABALLO_ELIMINAR = 'CABALLO_ELIMINAR'
export const CABALLO_ACTUALIZAR = 'CABALLO_ACTUALIZAR'
export const CABALLO_ERROR = 'CABALLO_ERROR'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'